version: "3.9"
services:
  health-check:
    # image: nirmalyas/my-rust-tutorial-health:0.1
    image: my-rust-tutorial-health:0.1
    # build:
    #   context: .
    #   dockerfile: Dockerfile-health
    restart: "always"
    depends_on:
      auth:
        condition: service_started
  auth:
    # image: nirmalyas/my-rust-tutorial-auth:0.1
    image: my-rust-tutorial-auth:0.1
    # build:
    #   context: .
    #   dockerfile: Dockerfile-auth
    restart: "always"
    ports:
      - "50051:50051"